version: '3.7'
services:
  service:
    build: .
    ports:
      - 3000:3000
    restart: always
    environment:
      - NEXT_PUBLIC_MAINNET=56
      - NEXT_PUBLIC_TESTNET=97
      - NEXT_PUBLIC_CHAIN_ID=42
      - NEXT_PUBLIC_MAINNET_URL=https://bscscan.com
      - NEXT_PUBLIC_TESTNET_URL=https://kovan.etherscan.io
      - NEXT_PUBLIC_NODE_1=https://bsc-dataseed1.ninicoin.io
      - NEXT_PUBLIC_NODE_2=https://bsc-dataseed1.defibit.io
      - NEXT_PUBLIC_NODE_3=https://bsc-dataseed.binance.org
      - NEXT_PUBLIC_UAUTH_CLIENT_ID_UNSTOPPABLE=25c2c9be-47cd-4b47-a082-3120417dc5a7
      - NEXT_PUBLIC_UAUTH_REDIRECT_URI_UNSTOPPABLE=http://localhost:3000
      - NEXT_PUBLIC_UAUTH_POST_LOGOUT_REDIRECT_URI_UNSTOPPABLE=http://localhost:3000
      - NEXT_PUBLIC_TRANSAK_BASE_URL=https://staging-global.transak.com
      - NEXT_PUBLIC_TRANSAK_API_KEY=59eec62d-18c0-4ca8-9511-3fa70cfeaebb
      - NEXT_PUBLIC_TRANSAK_REDIRECT_URL=http://localhost:3000